openapi: 3.1.0
info:
  title: Polygon Stock API
  description: Consulta datos históricos usando Polygon.io.
  version: 1.0.0
servers:
  - url: https://api.polygon.io
paths:
  /v2/aggs/ticker/{ticker}/prev:
    get:
      operationId: getPreviousClose
      summary: Datos del cierre previo de una acción
      description: Devuelve datos del cierre del día anterior de una acción.
      parameters:
        - name: ticker
          in: path
          required: true
          description: Símbolo del ticker de la acción (por ejemplo, MSFT, AAPL).
          schema:
            type: string
        - name: apiKey
          in: query
          required: true
          description: Tu clave API de Polygon.io.
          schema:
            type: string
      responses:
        '200':
          description: Respuesta exitosa con datos del cierre previo.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ticker:
                    type: string
                    description: Símbolo del ticker.
                  queryCount:
                    type: integer
                    description: Número de resultados encontrados.
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        close:
                          type: number
                          description: Precio de cierre.
                        volume:
                          type: integer
                          description: Volumen de acciones.
                        timestamp:
                          type: integer
                          description: Marca de tiempo del cierre.
        '401':
          description: Error de autorización.
